
// SearchBar
export const LOAD_SEARCHBAR_CONFIG = 'LOAD_SEARCHBAR_CONFIG';
export const SELECT_SEARCH_ENGINE = 'SELECT_SEARCH_ENGINE';
export const ADD_SEARCH_ENGINE = 'ADD_SEARCH_ENGINE';
export const UPDATE_SEARCH_ENGINE = 'UPDATE_SEARCH_ENGINE';
export const DELETE_SEARCH_ENGINE = 'DELETE_SEARCH_ENGINE'
export const SEARCH_IN_NEW_TAB_TRUE = 'SEARCH_IN_NEW_TAB_TRUE';
export const SEARCH_IN_NEW_TAB_FALSE = 'SEARCH_IN_NEW_TAB_FALSE';